### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by Saloed** [rembl/Tail#1]
1. Может просто вынести main в TailLauncher, а то какая-то запутанная логика получается. Tail вызывает Launcher, который потом вызывает какой-то статический метод у Tail. [link](https://github.com/rembl/Tail/blob/de0bc4cf2b51b18ad57adec7573f7abe6286f653/src/main/java/Tail/Tail.java#L11)
2. Лучше сделать это обычными полями, а в hopper создать объект Tail и с ним работать. [link](https://github.com/rembl/Tail/blob/de0bc4cf2b51b18ad57adec7573f7abe6286f653/src/main/java/Tail/Tail.java#L14)
3. Кажется, это лучше сделать `enum`, а не строкой. [link](https://github.com/rembl/Tail/blob/de0bc4cf2b51b18ad57adec7573f7abe6286f653/src/main/java/Tail/Tail.java#L14)
4. Tail очень часто используют, когда имеется очень большой файл, (например лог на 10^9 строк), а нужно посмотреть только хвост этого файла, (например, последние 100 строк). Вычитывать весь файл в таком случае будет очень долго и настоящий tail так не делает. Вместо этого, есть способ сразу потыкаться в конец файла. Например, можно используя [вот это](https://docs.oracle.com/javase/7/docs/api/java/io/RandomAccessFile.html). С стандартным потоком ввода (System.in) так не получится и там нужно будет что-то придумать. В результате, хотелось бы увидеть:
   - Интерфейс для чтения строк, который предоставляет утилите всё что нужно
   - Реализацию этого интерфейса для чтения из файла
   - Реализацию для чтения из stdin
4. Не хватает тестов.

**Comment by Saloed** [comment]
1. А что, если `number > file.length()`? [link](https://github.com/rembl/Tail/blob/9b08dda7fecf97b14b6806c765c8b6f36a706e54/src/main/java/Tail/Tail.java#L36)
2. Было бы хорошо объединить этот кусок, с тем который ниже для символов, ведь они делают одно и то же. [link](https://github.com/rembl/Tail/blob/9b08dda7fecf97b14b6806c765c8b6f36a706e54/src/main/java/Tail/Tail.java#L28)
3. А это точно корректно работает для нескольких файлов? [link](https://github.com/rembl/Tail/blob/9b08dda7fecf97b14b6806c765c8b6f36a706e54/src/main/java/Tail/Tail.java#L44)
4. Пустая строка не означает, что поток закончился. Там другой признак конца. [link](https://github.com/rembl/Tail/blob/9b08dda7fecf97b14b6806c765c8b6f36a706e54/src/main/java/Tail/Tail.java#L54)
5. А зачем здесь вычитывать всю строку? Здесь можно спокойно вычитывать по одному символу, поскольку это BufferedReader, и он сам затягивает полный буфер символов, когда это нужно. А так, он просто возвращает символ из буфера. [link](https://github.com/rembl/Tail/blob/9b08dda7fecf97b14b6806c765c8b6f36a706e54/src/main/java/Tail/Tail.java#L65)
6. **Пункт 5 из предыдущего списка.**

**Comment by Saloed** [comment]
1. Что это за хитрая логика с `+3`? [link](https://github.com/rembl/Tail/blob/a45b0e9fb8be904a3ff040dedce4a96759313841/src/main/java/Tail/Tail.java#L32)
2. Обычное, если tail видит, что у него попросили прочитать больше, чем есть, то он просто читает всё, что есть. [link](https://github.com/rembl/Tail/blob/a45b0e9fb8be904a3ff040dedce4a96759313841/src/main/java/Tail/Tail.java#L36)
3. Если сделать не статический метод, а обычный, то `Tail` можно будет не передавать аргументом. [link](https://github.com/rembl/Tail/blob/a45b0e9fb8be904a3ff040dedce4a96759313841/src/main/java/Tail/Tail.java#L17)
4. Прочитайте внимательнее, как работает [`readLine`](https://docs.oracle.com/javase/8/docs/api/java/io/BufferedReader.html#readLine-- ). Он умеет сообщать, что строк больше нет.
5. Лучше разделить это на 2 теста. [link](https://github.com/rembl/Tail/blob/a45b0e9fb8be904a3ff040dedce4a96759313841/src/test/java/Tail/TailTest.java#L27)
6. Есть такая штука -- [StringReader](https://docs.oracle.com/javase/7/docs/api/java/io/StringReader.html). Можно использовать и код в тестах станет попроще. [link](https://github.com/rembl/Tail/blob/a45b0e9fb8be904a3ff040dedce4a96759313841/src/test/java/Tail/TailTest.java#L56)
7. Если вы используете `FileUtils`, то там уже есть методы, которые позволяют сравнить содержимое файлов. Например, [`contentEquals`](https://commons.apache.org/proper/commons-io/javadocs/api-2.5/org/apache/commons/io/FileUtils.html#contentEquals(java.io.File,%20java.io.File))

**Comment by rembl** [comment]
1. Каретка сдвигается на предыдущую строку, читает ее \n, а потом еще сдвигается назад, поэтому приходится продвигать ее вперед, чтобы читать с начала нужной строки.
2. -- 6. Исправила
7. Когда использую contentEquals (я поняла, что он проверяет побайтово), то тесты не проходят, а когда проверяю построчно, то все работает. Не знаете, с чем это может быть связано?

**Comment by Saloed** [comment]
`1.` ok
`3.` Дело в том, что на различных операционных системах используются различные признаки конца строки. Например, в Linux используется LF (`\n`), а в Windows используется CRLF (`\r\n`). Посмотреть признак конца строки в java можно используя функцию [`System.lineSeparator`](https://docs.oracle.com/javase/8/docs/api/java/lang/System.html#lineSeparator--).  В тестах у вас сейчас используется `contentEqualsIgnoreEOL`, который решает эту проблему тем, что игнорирует признак конца строки при сравнении.
